//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gallery_mk4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artwork
    {
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> ExhibitionID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> MediumID { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Exhibitions Exhibitions { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Location Location { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
