//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gallery_mk4.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PictureGalleryEntities : DbContext
    {
        public PictureGalleryEntities()
            : base("name=PictureGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artwork> Artwork { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Medium> Medium { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
