//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gallery_mk4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
